---
title: "Answers to Exercises: Perfect Multicollinearity in LM"
author: "Alexandre Courtiol"
date: "`r Sys.Date()`"
output: 
  html_vignette
vignette: >
  %\VignetteIndexEntry{2.X Answers to Exercises: Perfect Multicollinearity in LM}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---
```{r setup, include=FALSE}
library(LM2GLMM)
knitr::opts_chunk$set(cache = FALSE, fig.align = "center", fig.width = 5, fig.height = 5)
```

## Preparing the data

```{r}
FungiAlive <- subset(Fungi, alive == TRUE)
```

## Silly attempt

```{r, error=TRUE}
coef(mod_silly <- lm(growth ~ species* (T36 + T38 + PT36 + PT38), data = FungiAlive))
(XTX <- crossprod(model.matrix(~ species* (T36 + T38 + PT36 + PT38), data = FungiAlive)))
det(XTX)  ## bad --> this model won't work
solve(XTX)
caret::findLinearCombos(model.matrix(mod_silly))
```

## Looking at the data structure (ignoring species for now)

```{r}
with(FungiAlive, table(T36, T38, PT36, PT38))  ## cumbersome
crossprod(model.matrix(~ T36 + T38 + PT36 + PT38, data = FungiAlive)) ## more efficient
```

## Creating the pre-treatment variable

```{r}
FungiAlive$PT <- "no"
FungiAlive$PT[FungiAlive$PT36 == 1] <- "36"
FungiAlive$PT[FungiAlive$PT38 == 1] <- "38"
FungiAlive$PT <- factor(FungiAlive$PT)
table(FungiAlive$PT, FungiAlive$species)
```

## Creating the treatment variable

```{r}
FungiAlive$T <- "no"
FungiAlive$T[FungiAlive$T36 == 1] <- "36"
FungiAlive$T[FungiAlive$T38 == 1] <- "38"
FungiAlive$T <- factor(FungiAlive$T)
table(FungiAlive$T, FungiAlive$species)
```


## Fitting the model and predicting the effects: solution 1

```{r}
X <- model.matrix(~ species * (PT + T), data = FungiAlive)
(XTX <- crossprod(X))
det(XTX)

(m2 <- lm(growth ~ species * (PT + T), data = FungiAlive))
newdata2 <- data.frame(PT = c("36", "38", "no", "no", "36", "38", "no", "no"),
                       T = c("36", "38", "36", "38", "36", "38", "36", "38"),
                       species = c(rep("M_A", 4), rep("M_B", 4)))
newdata2$pred <- predict(m2, newdata = newdata2)
newdata2
```

```{r}
plot(newdata2[newdata2$species == "M_A", "pred"],
     type = "b", axes = FALSE, col = "red",
     ylim = range(newdata2$pred),
     ylab = "Growth rate", xlab = "Experimental condition")
points(newdata2[newdata2$species == "M_B", "pred"],
       type = "b", col = "blue")
axis(side = 2, las = 1)
axis(side = 1, at = 1:4,
     labels = c("36_36", "38_38", "no_36", "no_38"))
box()
legend("top", pch = c(1, 1), col = c("blue", "red"), horiz = TRUE,
       legend = c("M_A", "M_B"), box.lty = 2, title = "Species")
```


## Fitting the model and predicting the effects: solution 2

```{r}
FungiAlive$condition <-
  factor(paste(FungiAlive$species, FungiAlive$PT, FungiAlive$T, sep = "_"))
  table(FungiAlive$condition)
```


```{r}
X <- model.matrix(~ -1 + condition, data = FungiAlive)
(XTX <- crossprod(X))
det(XTX)

m1 <- lm(growth ~ -1 + condition, data = FungiAlive)
data.frame(coef(m1))
newdata1 <- data.frame(condition = levels(FungiAlive$condition))
newdata1$pred <- predict(m1, newdata = newdata1)
```

```{r}
plot(c(
  newdata1[newdata1$condition == "M_A_36_36", "pred"],
  newdata1[newdata1$condition == "M_A_38_38", "pred"],
  newdata1[newdata1$condition == "M_A_no_36", "pred"],
  newdata1[newdata1$condition == "M_A_no_38", "pred"]),
  type = "b", axes = FALSE, col = "red",
  ylim = range(newdata1$pred),
  ylab = "Growth rate", xlab = "Experimental condition")
points(c(
  newdata1[newdata1$condition == "M_B_36_36", "pred"],
  newdata1[newdata1$condition == "M_B_38_38", "pred"],
  newdata1[newdata1$condition == "M_B_no_36", "pred"],
  newdata1[newdata1$condition == "M_B_no_38", "pred"]),
  type = "b", col = "blue")
axis(side = 2, las = 1)
axis(side = 1, at = 1:4,
     labels = c("36_36", "38_38", "no_36", "no_38"))
box()
legend("top", pch = c(1, 1), col = c("blue", "red"), horiz = TRUE,
       legend = c("M_A", "M_B"), box.lty = 2, title = "Species")
```


