---
title: "LM: fitting procedures"
subtitle: "exercises"
author: "Alexandre Courtiol"
date: "`r Sys.Date()`"
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
vignette: >
  %\VignetteIndexEntry{2.1 z-------------------------------------------------------------exercises}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
library(LM2GLMM)
knitr::opts_chunk$set(cache = FALSE)
options(width = 110)
set.seed(1L)
```

## Fitting a LM with REML estimation of the error variance

Adapt the code shown in the course to compute the log-likelihood of the fit as the function of the error variance estimate rather than the population residual variance.

As in the course, use `size ~ humans_eaten` as the formula and the following data:

```{r}
set.seed(123)
Alien <- simulate_Aliens()
```

Compare the results with the outcome of the following call:

```{r, message=FALSE}
library(spaMM)
fit_spaMM_REML <- fitme(size ~ humans_eaten, data = Alien, method = "REML")
```


##

<div align="right">
[Back to main menu](./Title.html#2)
</div>
